In [1]:
import pandas as pd

doc = []
with open('dates.txt') as file:
    for line in file:
        doc.append(line)

df = pd.Series(doc)
df.tail(10)

490                                  Lab: B12 969 2007\n
491                                   )and 8mo in 2009\n
492    .Moved to USA in 1986. Suffered from malnutrit...
493                                              r1978\n
494    . Went to Emerson, in Newfane Alaska. Started ...
495    1979 Family Psych History: Family History of S...
496    therapist and friend died in ~2006 Parental/Ca...
497                         2008 partial thyroidectomy\n
498    sPt describes a history of sexual abuse as a c...
499    . In 1980, patient was living in Naples and de...
dtype: object

In [215]:

# First need to extract all the dates from the series
dates = df.str.extract(r'((\d?\d)/(\d?\d)/(\d?\d)|(\d{4})|(\d?\d)-(\d?\d)-(\d?\d))') # REGEX to extract all the dates
print(dates)

print(dates[0].isnull().sum())
print(dates[dates[0].isnull()])  # We get 25, 39 and 71 are NaNs

print(df[25], df[39], df[71], df[271])

            0    1    2    3     4    5    6    7
0    03/25/93   03   25   93   NaN  NaN  NaN  NaN
1     6/18/85    6   18   85   NaN  NaN  NaN  NaN
2      7/8/71    7    8   71   NaN  NaN  NaN  NaN
3     9/27/75    9   27   75   NaN  NaN  NaN  NaN
4      2/6/96    2    6   96   NaN  NaN  NaN  NaN
5     7/06/79    7   06   79   NaN  NaN  NaN  NaN
6     5/18/78    5   18   78   NaN  NaN  NaN  NaN
7    10/24/89   10   24   89   NaN  NaN  NaN  NaN
8      3/7/86    3    7   86   NaN  NaN  NaN  NaN
9     4/10/71    4   10   71   NaN  NaN  NaN  NaN
10    5/11/85    5   11   85   NaN  NaN  NaN  NaN
11    4/09/75    4   09   75   NaN  NaN  NaN  NaN
12    8/01/98    8   01   98   NaN  NaN  NaN  NaN
13    1/26/72    1   26   72   NaN  NaN  NaN  NaN
14    5/24/19    5   24   19   NaN  NaN  NaN  NaN
15    1/25/20    1   25   20   NaN  NaN  NaN  NaN
16    4/12/82    4   12   82   NaN  NaN  NaN  NaN
17   10/13/19   10   13   19   NaN  NaN  NaN  NaN
18    4/24/98    4   24   98   NaN  NaN  NaN  NaN
19    5/21/77    5   21   77   NaN  NaN  NaN  NaN
20    7/21/98    7   21   98   NaN  NaN  NaN  NaN
21   10/21/79   10   21   79   NaN  NaN  NaN  NaN
22    3/03/90    3   03   90   NaN  NaN  NaN  NaN
23    2/11/76    2   11   76   NaN  NaN  NaN  NaN
24   07/25/19   07   25   19   NaN  NaN  NaN  NaN
25    4-13-82  NaN  NaN  NaN   NaN    4   13   82
26    9/22/89    9   22   89   NaN  NaN  NaN  NaN
27    9/02/76    9   02   76   NaN  NaN  NaN  NaN
28    9/12/71    9   12   71   NaN  NaN  NaN  NaN
29   10/24/86   10   24   86   NaN  NaN  NaN  NaN
..        ...  ...  ...  ...   ...  ...  ...  ...
470      1983  NaN  NaN  NaN  1983  NaN  NaN  NaN
471      1999  NaN  NaN  NaN  1999  NaN  NaN  NaN
472      2010  NaN  NaN  NaN  2010  NaN  NaN  NaN
473      1975  NaN  NaN  NaN  1975  NaN  NaN  NaN
474      1972  NaN  NaN  NaN  1972  NaN  NaN  NaN
475      2015  NaN  NaN  NaN  2015  NaN  NaN  NaN
476      1989  NaN  NaN  NaN  1989  NaN  NaN  NaN
477      1994  NaN  NaN  NaN  1994  NaN  NaN  NaN
478      1993  NaN  NaN  NaN  1993  NaN  NaN  NaN
479      1996  NaN  NaN  NaN  1996  NaN  NaN  NaN
480      2013  NaN  NaN  NaN  2013  NaN  NaN  NaN
481      1974  NaN  NaN  NaN  1974  NaN  NaN  NaN
482      1990  NaN  NaN  NaN  1990  NaN  NaN  NaN
483      1995  NaN  NaN  NaN  1995  NaN  NaN  NaN
484      2004  NaN  NaN  NaN  2004  NaN  NaN  NaN
485      1987  NaN  NaN  NaN  1987  NaN  NaN  NaN
486      1973  NaN  NaN  NaN  1973  NaN  NaN  NaN
487      1992  NaN  NaN  NaN  1992  NaN  NaN  NaN
488      1977  NaN  NaN  NaN  1977  NaN  NaN  NaN
489      1985  NaN  NaN  NaN  1985  NaN  NaN  NaN
490      2007  NaN  NaN  NaN  2007  NaN  NaN  NaN
491      2009  NaN  NaN  NaN  2009  NaN  NaN  NaN
492      1986  NaN  NaN  NaN  1986  NaN  NaN  NaN
493      1978  NaN  NaN  NaN  1978  NaN  NaN  NaN
494      2002  NaN  NaN  NaN  2002  NaN  NaN  NaN
495      1979  NaN  NaN  NaN  1979  NaN  NaN  NaN
496      2006  NaN  NaN  NaN  2006  NaN  NaN  NaN
497      2008  NaN  NaN  NaN  2008  NaN  NaN  NaN
498      2005  NaN  NaN  NaN  2005  NaN  NaN  NaN
499      1980  NaN  NaN  NaN  1980  NaN  NaN  NaN

[500 rows x 8 columns]
0
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
4-13-82 Other Child Mental Health Outcomes Scales Used:
 1-14-81 Communication with referring physician?: Done
 4-13-89 Communication with referring physician?: Not Done
 .Spoke to sister Naomi Ely 708-810-7787 who reports he has been doing much better since he went to Dysart Clinic (he was drinking for a month leading up to this, his ammonia was high, and physicians were worried about early).  She feels his cognition is back to baseline, "100% better".  She says he has been successful in abstaining from substances as far as she knows, thinks a schedule is useful to him, doctor's appts etc.  Notes that he returned from LA in August 2008, gets bouts of "exhaustion" even in sobriety.  She denies ever witnessing any periods of manic behavior from patient.  Their father has dementia that started at age 84.  Notes patient is living with uncle in Black River Falls (uncle is 89), lived with sister 3 months who also takes care of her own father in Talladega.  She knows he is working on getting social security, subsidizing housing.  Stable situation with patient's girlfriend Nutt.Suicidal Behavior Hx of Suicidal Behavior: No

/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  app.launch_new_instance()

In [109]:


#print([w.str.cat(['1', '1'], sep='/') for w in dates_final if len(dates_final) == 4])

dates_final = pd.DataFrame(dates_final)
dates_final['new_col'] = 0
dates_final = dates_final.rename(index= str, columns={'0': 'col'})

print(dates_final.head())

print(len(dates_final.iloc[498, 0]))

for index in dates_final.iterrows() :
    if len(dates_final.iloc[index, 0]) == 4 :
        #row.replace(row, ('1/1/'+ row))   
        dates_final.new_col = 1

#pd.to_datetime(dates_final) 

case = len(dates_final.iloc[:, 0]) == 4
dates_final.loc[case, ] =  '1/1/' + str(dates_final.iloc[:, 0])
#years = dates_final.str[-2:]
#print(dates_final.tail())

          0  new_col
0  03/25/93        0
1   6/18/85        0
2    7/8/71        0
3   9/27/75        0
4    2/6/96        0
4

IndexingError: Too many indexers

In [221]:
import numpy as np
import datetime as dt 
dates_final = dates[0]
dates_final = pd.Series(dates_final)
dates_final = dates_final.str.replace('-', '/')
data = np.array(dates_final)
data = pd.DataFrame(data)
data.columns = ['col']
 
data['new_col'] = 0 
# create a column for the years
data['years']= data.col.str[-2:] 
data['years1'] = np.where(data.years < '20', ('20' + data.years), ('19' + data.years))
data['new_col']  = np.where(data['col'].str.len() == 4, '1/1/' + data.col, data.col.str[:-2] + data.years1)

data= data.loc[:, 'new_col'] 
data[271] = '08/01/2008'
data = pd.to_datetime(data, format = '%m/%d/%Y' )
print(data.head())
a = data.rank(method='dense').sub(1).astype(int) 
print(a)

0   1993-03-25
1   1985-06-18
2   1971-07-08
3   1975-09-27
4   1996-02-06
Name: new_col, dtype: datetime64[ns]
0      113
1       74
2       12
3       31
4      124
5       48
6       44
7       94
8       76
9       10
10      73
11      29
12     134
13      16
14     160
15       0
16      58
17     168
18     132
19      39
20     133
21      50
22      96
23      34
24     162
25      59
26      93
27      35
28      14
29      78
      ...
470     65
471    137
472    149
473     27
474     15
475    154
476     89
477    115
478    112
479    123
480    152
481     23
482     95
483    118
484    142
485     80
486     20
487    106
488     37
489     72
490    145
491    148
492     75
493     42
494    140
495     47
496    144
497    146
498    143
499     51
Name: new_col, Length: 500, dtype: int64

In [ ]:
years = pd.DataFrame(years)
years['new_col'] = np.where(years < '20', ('20' + years), ('19' + years))
years.tail()
years = years.loc[:, 'new_col']
years.head()
print(type(years))

# Need to sort the years
a = years.rank(method='dense').sub(1).astype(int)
print(a)